sudo: false

language: node_js

node_js:
  - "12"
  - "10"
  - "8"

before_install:
  - npm cache clean --force
  - npm install -g mocha coveralls

after_success:
  - npm run coveralls

script:
  - npm test
